import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { ClientLayout } from "@/components/ClientLayout"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative bg-white min-h-screen ${geistSans.variable}`}>
        <div className="fixed inset-0 bg-white z-[-1]" />
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  )
}
